all: shell
	./shell


shell: shell.c
	gcc shell.c -o shell -Wall



#saida: teste.o saida.o
        # O compilador faz a ligação entre os dois objetos
#	nvcc -o saida teste.o saida.o
#-----> Distancia com o botão TAB ### e não com espaços
#teste.o: teste.c
#	g++ -o teste.o -c teste.cpp
#saida.o: teste.cu teste.h
#	nvcc -o saida.o -c teste.cu